# Site settings
title: Chè Nxusani
email: che.nxusani@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey, I'm Chè Nxusani, a software developer building applications for the web. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chenxusani.com" # the base hostname & protocol for your site
twitter_username: code_dependant
github_username:  codedependant
codepen_username:  code_dependant

# Build settings
markdown: kramdown